// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABLljDCkCMaJ69QheOC4WftddPQoHdmqw',
    appId: '1:666794413313:web:2191aa90ddce2abd6c1f00',
    messagingSenderId: '666794413313',
    projectId: 'act14-243f7',
    authDomain: 'act14-243f7.firebaseapp.com',
    storageBucket: 'act14-243f7.firebasestorage.app',
    measurementId: 'G-VE1ZSFH6P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtpuDDV11SJ5slcia5tW3GXJyay_N8Qlg',
    appId: '1:666794413313:android:291621c655de11b46c1f00',
    messagingSenderId: '666794413313',
    projectId: 'act14-243f7',
    storageBucket: 'act14-243f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu3LXRTYjA4K1wKwZuAB3gCi8BNjuWAfo',
    appId: '1:666794413313:ios:7dc894d4dc4262f16c1f00',
    messagingSenderId: '666794413313',
    projectId: 'act14-243f7',
    storageBucket: 'act14-243f7.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu3LXRTYjA4K1wKwZuAB3gCi8BNjuWAfo',
    appId: '1:666794413313:ios:7dc894d4dc4262f16c1f00',
    messagingSenderId: '666794413313',
    projectId: 'act14-243f7',
    storageBucket: 'act14-243f7.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABLljDCkCMaJ69QheOC4WftddPQoHdmqw',
    appId: '1:666794413313:web:1fc590970f68c25d6c1f00',
    messagingSenderId: '666794413313',
    projectId: 'act14-243f7',
    authDomain: 'act14-243f7.firebaseapp.com',
    storageBucket: 'act14-243f7.firebasestorage.app',
    measurementId: 'G-X7R3Q5J3R5',
  );
}
